## Transposición de matriz

#### Basicamente es: transformar las filas de la matriz en las nuevas columnas y las columnas se convierten en las filas.

In [7]:
# Ejemplo 1 
import pandas as pd
import numpy as np

matrix = np.array([
    [1, 2], 
    [4, -4], 
    [0, 17]])

print('Matriz original')
print(matrix)
print()
print('Matriz transpuesta')
print()
print(matrix.T)

# Intentemos multiplicar la matriz original por un vector con una longitud de 3:
vector = [2, 1, -1] 

print() 

print(np.dot(matrix.T, vector)) # si usamos la matriz sin Transponer la dara error

Matriz original
[[ 1  2]
 [ 4 -4]
 [ 0 17]]

Matriz transpuesta

[[ 1  4  0]
 [ 2 -4 17]]

[  6 -17]


In [8]:
# Ejercicio 1 Calcula cuánto material se necesitará para producir 16 mesas, 60 sillas y 4 bancos. 
# Guarda el resultado en la variable de materiales y muestra el resultado en la pantalla (en precódigo).

materials_names = ['Tabla', 'Tubos', 'Tornillos']

manufacture = np.array([ # Tenemos laMtriz
    [0.2, 1.2, 8],
    [0.5, 0.8, 6],
    [0.8, 1.6, 8]])

furniture = [60, 4, 16] # Tenmos el Vector

materials = (np.dot(manufacture.T, furniture)) # multiplicamospara sacar el resultado deseado

print(pd.DataFrame([materials], index=[''], columns=materials_names)) 

  Tabla  Tubos  Tornillos
   26.8  100.8      632.0


## Multiplicación de matrices




##### Recuerda que en la multiplicación matriz-vector construimos un nuevo vector donde cada elemento era el producto escalar de una fila de la matriz y el vector. Durante la multiplicación de matrices, se construye una tercera matriz usando dos matrices. 

In [10]:
# En Numpy hay tres formas de multiplicar matrices
A = np.array([
    [1, 2, 3], 
    [-1, -2, -3]])

B = np.array([
    [1, 0], 
    [0, 1],
    [1, 1]])

print(np.dot(A,B)) 
print()
print(A.dot(B))
print() 
print(A @ B)

[[ 4  5]
 [-4 -5]]

[[ 4  5]
 [-4 -5]]

[[ 4  5]
 [-4 -5]]


In [ ]:
# Ejemplo 2 Supongamos que tienes un hotel con dos tipos de habitaciones: suites de luna de miel y habitaciones individuales normales. Una suite de luna de miel cuesta 700 dólares la noche y una habitación normal cuesta 50 dólares.
# El primer periodo es de febrero a marzo. El segundo es un periodo de tres meses de verano. 
# Para saber cuánto dinero ganó nuestro hotel cada mes, debemos multiplicar costs y bookings.
# La matriz resultante se puede pasar fácilmente a un DataFrame para mostrar los resultados.

months_1 = ['February', 'March'] # Primer periodo
months_2 = ['June', 'July', 'August'] # Segundo periodo

costs = np.array([
    # honeymoon_suite, regular
    [700, 50]
])

bookings_1 = np.array([ # Numero de reservas primer periodo
    [3, 4],
    [17, 26]
])

bookings_2 = np.array([ # Numero de reservas segundo periodo
    [8, 9, 11],
    [21, 26, 30]
])

print(pd.DataFrame((costs @ bookings_1), columns=months_1))
print('----------------------')
print(pd.DataFrame((costs @ bookings_2), columns=months_2))

   February  March
0      2950   4100
----------------------
   June  July  August
0  6650  7600    9200


In [ ]:
# Ejericico 2

# T-phone está de vuelta con otra tarea. Tienes una matriz que contiene datos sobre los paquetes de contenido de los clientes durante un mes.
# Calcula la cantidad de minutos, mensajes de texto y megabytes gastados por todos los clientes durante el mes.
# Muestra en la pantalla el resultado en la matriz clients_services con filas correspondientes a clientes y columnas correspondientes a servicios.

services = ['Minutos', 'Mensajes', 'Megabytes']
packs_names = ['"Detrás del volante', '"En el metro"']
packs = np.array([
    [20, 5],
    [2, 5],
    [500, 1000]])

clients_packs = np.array([
    [1, 2],
    [2, 3],
    [4, 1],
    [2, 3],
    [5, 0]])

print('Paquetes')
print(pd.DataFrame(clients_packs, columns=packs_names))
print()

clients_services = (clients_packs.dot(packs.T))

print('Minutos, Mensajes y Megabytes')
print(pd.DataFrame(clients_services, columns=services))
print()




Paquetes
   "Detrás del volante  "En el metro"
0                    1              2
1                    2              3
2                    4              1
3                    2              3
4                    5              0

Minutos, Mensajes y Megabytes
   Minutos  Mensajes  Megabytes
0       30        12       2500
1       55        19       4000
2       85        13       3000
3       55        19       4000
4      100        10       2500



In [39]:
# Ejercicio 3 
# Roble y Pino ha recibido pedidos de muebles de varios lugares diferentes y necesitan saber las cantidades de los materiales que necesitan para cumplir con los pedidos. Como antes, la matriz manufacture muestra los materiales necesarios para cada uno de los diferentes tipos de muebles, 
# donde las filas son los tipos de muebles (silla, banca y mesa) y las columnas son los materiales. Por ejemplo, para hacer una silla, necesitamos 0.2 metros de tabla, 1.2 metros de tubo de metal y 8 tornillos.
# La matriz furniture muestra el número de cada mueble en los diferentes lugares: una cafetería, un comedor y un restaurante, donde las filas son los lugares y las columnas son los tipos de muebles. Por ejemplo, la cafetería necesita 12 sillas, 0 bancas y 3 mesas.
# Encuentra la matriz venues_materials, que contiene la cantidad de materiales (columnas) para cada establecimiento (filas). Muestra el resultado en pantalla (en precódigo).
# Calcula la cantidad de materiales necesarios para la producción de muebles si el pedido se recibió de 18 cafeterías, 12 comedores y 7 restaurantes. Guarda este vector en la variable total_materials y muéstralo en la pantalla (en precódigo).

materials_names = ['Tabla', 'Tubos', 'Tornillos']
venues_names = ['Cafetería', 'Comedor', 'Restaurante']

manufacture = np.array([
    [0.2, 1.2, 8],    # materiales para silla
    [0.5, 0.8, 6],    # materiales para banco
    [0.8, 1.6, 8]])   # materiales para mesa

furniture = np.array([
    [12, 0, 3],   # Pedido de cafetería (silla, banca, mesa)
    [40, 2, 10],  # Pedido de comedor
    [60, 6, 18]]) # Pedido de restaurante

venues_materials = furniture @ manufacture # < escribe tu código aquí >

print('Por el establecimiento')
print(pd.DataFrame(venues_materials, index=venues_names, columns=materials_names))
print()

venues = [18, 12, 7]
venues = np.array(venues)

total_materials = (venues_materials.T @ venues)# duda para la clase (venues.dot(venues_materials.T))

print('Total')
print(pd.DataFrame([total_materials], index=[''], columns=materials_names))

Por el establecimiento
             Tabla  Tubos  Tornillos
Cafetería      4.8   19.2      120.0
Comedor       17.0   65.6      412.0
Restaurante   29.4  105.6      660.0

Total
  Tabla   Tubos  Tornillos
  496.2  1872.0    11724.0


In [ ]:
Notas: Tener cuidado con el orden en la operacion 