## Creación de matrices

##### Matriz se puede interpretar como filas de vectores o columnas de vectores, donde cada vector es una lista de números que pueden estar en una fila o en una columna.

In [7]:
# Puedes crear una matriz en Python usando la función np.array()
# Solo necesitas una lista de listas con lamisma longitud

import numpy as np

matrix = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix)


pythonmatrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(pythonmatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:


vector1 = np.array([1, 2, 3])
vector2 = np.array([-1, -2, -3])

list_of_vectors = [vector1, vector2]

matrix_from_vectors = np.array(list_of_vectors)

print(list_of_vectors)
print(matrix_from_vectors)

[array([1, 2, 3]), array([-1, -2, -3])]
[[ 1  2  3]
 [-1 -2 -3]]


In [ ]:
#usando pandas
import pandas as pd

df = pd.DataFrame({'a': [120, 60, 75], 'b': [42, 50, 90]})
matrix = df.values
print(df)
print()
print(matrix)

A = np.array([
    [1, 2, 3], 
    [2, 3, 4]])

print('Tamaño:', A.shape) #shape funcion para ver el tamano  de filas y columnas


matrix = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9],
    [10,11,12]])

print('Primera fila:', matrix[0, :]) #asi se selecciona una fila y toda la columna dentro de la matriz
print('Tercera columna:', matrix[:, 2]) #asi se selecciona una columan  y toda la fila  dentro de la matriz

     a   b
0  120  42
1   60  50
2   75  90

[[120  42]
 [ 60  50]
 [ 75  90]]


In [ ]:
# Ejercicio 1
# A partir de una lista de filas, crea una matriz de 2×3 donde la primera fila contenga los números 3, 14, 159 y la segunda -2, 7, 183.

matrix = np.array ([[3, 14, 159], [-2, 7, 183]])

print(matrix)

# El operador de telefonía móvil T-phone quiere analizar los datos de uso diario de los clientes. 
# La tabla muestra la cantidad de mensajes de texto, minutos de conversación y megabytes de cinco clientes en el día lunes (monday).
# Convierte la tabla en una matriz y muéstrala en la pantalla (en precódigo).


monday_df = pd.DataFrame({'Minutos': [10, 3, 15, 27, 7], 
                          'Mensajes': [2, 5, 3, 0, 1], 
                          'Megabytes': [72, 111, 50, 76, 85]})
 
monday = monday_df.values

print(monday)

#Selecciona los datos para el cuarto cliente de la matriz resultante (¡cuidado con los índices!). Muestra el resultado en la pantalla.
print(monday[3])

#En la matriz monday, selecciona la cantidad de datos que utilizó cada cliente. Muestra el resultado en la pantalla.
print(monday[:,2])  

Notas: Recordar que siempre se comienza a enumerar desde el 0 

## Operaciones con elementos de matriz

In [31]:


matrix1 = np.array([
    [1, 2], 
    [3, 4]])

matrix2 = np.array([
    [5, 6], 
    [7, 8]])

print(f"{matrix1 + matrix2}\n")# se suman, restan y multiplican con sus iguales, tienen que tener las mismas dimensiones      
print(f"{matrix1 - matrix2}\n")# para hacer estos saltos de linea necesitas n y usar f con " y {}
print(matrix1 * matrix2) 
print()
print(np.multiply(matrix1, matrix2))
print()
print(f"{matrix1 * 2}\n") #se puede multiplicar toda la matriz por un solo elemento}")

[[ 6  8]
 [10 12]]

[[-4 -4]
 [-4 -4]]

[[ 5 12]
 [21 32]]

[[ 5 12]
 [21 32]]

[[2 4]
 [6 8]]



In [49]:
# El operador de telefonía móvil T-phone está de vuelta con los datos de los usuarios de toda la semana. 
# Unifica los datos en una matriz para la semana: monday (lunes), tuesday (martes), wednesday (miércoles), thursday (jueves), friday (viernes), saturday (sábado), sunday (domingo). 
# Muéstrala en la pantalla (en precódigo).
# Crea un pronóstico para el mes.
# Con base en datos semanales, averigüa cuánto usa cada cliente los servicios en promedio por día. 
# Luego multiplica este promedio por 30.4 (el número promedio de días en un mes).


services = ['Minutos', 'Mensajes', 'Megabytes']

monday = np.array([
    [10, 2, 72],
    [3, 5, 111],
    [15, 3, 50],
    [27, 0, 76],
    [7, 1, 85]])

tuesday = np.array([
    [33, 0, 108],
    [21, 5, 70],
    [15, 2, 15],
    [29, 6, 34],
    [2, 1, 146]])

wednesday = np.array([
    [16, 0, 20],
    [23, 5, 34],
    [5, 0, 159],
    [35, 1, 74],
    [5, 0, 15]])

thursday = np.array([
    [25, 1, 53],
    [15, 0, 26],
    [10, 0, 73],
    [18, 1, 24],
    [2, 2, 24]])

friday = np.array([
    [32, 0, 33],
    [4, 0, 135],
    [2, 2, 21],
    [18, 5, 56],
    [27, 2, 21]])

saturday = np.array([
    [28, 0, 123],
    [16, 5, 165],
    [10, 1, 12],
    [42, 4, 80],
    [18, 2, 20]])

sunday = np.array([
    [30, 4, 243],
    [18, 2, 23],
    [12, 2, 18],
    [23, 0, 65],
    [34, 0, 90]])

weekly = monday + tuesday + wednesday + thursday + friday + saturday + sunday# primero sumamos lasmatrices de los dias de la semana

print('En una semana')
display(pd.DataFrame(weekly, columns=services))
print()

forecast = np.round((weekly / 7) * 30.4).astype(int) # sacamos el promedio de lo que cada cliente lo uso por dia y lomultiplicamos por el 30.4 para obtener pronostico mensual
# < escribe tu código aquí >

print('Pronóstico para un mes')
display(pd.DataFrame(forecast, columns=services))

En una semana


Minutos  Mensajes  Megabytes
0      174         7        652
1      100        22        564
2       69        10        348
3      192        17        409
4       95         8        401


Pronóstico para un mes


Minutos  Mensajes  Megabytes
0      756        30       2832
1      434        96       2449
2      300        43       1511
3      834        74       1776
4      413        35       1741

### Multiplicar una matriz por un vector

#### Se pueden multiplicar matrices por vectores y al final te daran un vector

In [ ]:
# Numpy se puede encargar de esta operacion llamando a .dott()
    
matrix = np.array([
    [1, 2, 3], 
    [4, 5, 6]])

vector = np.array([7, 8, 9])

# función independiente - toma dos argumentos
print(np.dot(matrix, vector))
# método de la matriz - solo necesita un argumento
print(matrix.dot(vector))

# Los resultados que tenemos son la suma de cada resultado de lamultiplicacion entre matriz y vector
# Ejemplo: Fila 1: 1*7 + 2*8 + 3*9 = 7 + 16 + 27 = 50 
#          Fila 2: 4*7 + 5*8 + 6*9 = 28 + 40 + 54 = 122

[ 50 122]
[ 50 122]


In [ ]:
# Ejemplo practico
# T-phone. El operador de telefonía móvil ofrece dos paquetes de servicios de pago por uso: "Al volante" y "En el metro". 
# Cada uno incluye una cantidad fija de minutos de conversación, mensajes de texto y megas de Internet. En promedio, los usuarios pagan 4-5 paquetes por mes:

services = ['Minutos', 'Mensajes', 'Megabytes']
packs_names = ['"Al volante"', '"En el metro"']
packs = np.array([
    [20, 5],
    [2, 5],
    [500, 1000]])

print('Paquete contenido')
display(pd.DataFrame(packs, columns=packs_names, index=services))
print()

clients_packs = np.array([
    [1, 2],
    [2, 3],
    [4, 1],
    [2, 3],
    [5, 0]])

print('Paquete del cliente')
display(pd.DataFrame(clients_packs, columns=packs_names))
print()

Paquete contenido


"Al volante"  "En el metro"
Minutos              20              5
Mensajes              2              5
Megabytes           500           1000


Paquete del cliente


"Al volante"  "En el metro"
0             1              2
1             2              3
2             4              1
3             2              3
4             5              0

In [ ]:
# Ejercicio Final
# Calcula la cantidad de minutos, mensajes de texto y tráfico de Internet gastados por el segundo cliente en el transcurso del mes. 
# Guarda el resultado en la variable client_services y muéstralo en la pantalla (ya en el precódigo).


services = ['Minutos', 'Mensajes', 'Megabytes']
packs_names = ['"Al volante"', '"En el metro"']
packs = np.array([[20, 5], [2, 5], [500, 1000]])

clients_packs = np.array([[1, 2], [2, 3], [4, 1], [2, 3], [5, 0]])

print("Paquete del cliente")
print(pd.DataFrame(clients_packs[1], index=packs_names, columns=['']))
print()

client_vector = clients_packs[1, :] # selecciono al segundo cliente y le asgino una variable
client_services = np.dot(packs, client_vector) # usamos dot para calcular multiplica en este caso el cliente dos con los paquetes

print(pd.DataFrame(client_services.reshape(-1, 1), index=services, columns=["Totales"])) # mostramoslos resultados finales en un data frame para amnetenr orden


Paquete del cliente
                
"Al volante"   2
"En el metro"  3

           Totales
Minutos         55
Mensajes        19
Megabytes     4000


Notas: Index agrega al dataframe los nombres de esa variable
       Columns asigna el nombre a la variable si no existe se usan ""
       En este caso usamos .reshape(-1,1) por que convierte el vector de 1D en 2D